### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by switchtan** [tompro/RedisTools#1]
do i need to use require_once  all files?

**Comment by tompro** [comment]
You did notice that this project is unfinished and is no longer maintained? But to answer your question, you can look into the bootstrap.php file in the test directory which Registers a class loader (normally this should be automatic when adding the dependency to your Project). If you just need some specific functionality of this lib you should consider directory copying the code into your project.

**Comment by tompro** [comment]
You did notice that this project is unfinished and is no longer maintained? But to answer your question, you can look into the bootstrap.php file in the test directory which Registers a class loader (normally this should be automatic when adding the dependency to your Project). If you just need some specific functionality of this lib you should consider directly copying the code into your project.
